version: '3.4'

services:
  gamedatabase.api:
    image: ${DOCKER_REGISTRY-}gamedatabaseapi
    container_name: API
    build:
      context: .
      dockerfile: GameDatabase.API/Dockerfile
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-CU22-ubuntu-20.04"
    container_name: sql_server2019
    ports:
     - "1433:1433"
    environment:
     - ACCEPT_EULA=y
     - SA_PASSWORD=*ABcZ123#