version: '3.4'

services:
  gamedatabase.api:
    image: ${DOCKER_REGISTRY-}gamedatabaseapi
    container_name: API
    build:
      context: .
      dockerfile: GameDatabase.API/Dockerfile
    ports:
     - "5234:80"
     - "5235:443"
    depends_on:
     - sqlserver
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-CU22-ubuntu-20.04"
    container_name: sql_server2019
    ports:
     - "1433:1433"
    environment:
     - ACCEPT_EULA=y
     - SA_PASSWORD=*ABcZ123#
  mssqltools:
   image: "mcr.microsoft.com/mssql-tools"
   container_name: mssqltools
   depends_on:
    - sqlserver
   volumes:
    - ./dbinit/dbinit.sql:/tmp/dbinit/dbinit.sql
    - ./dbinit/seed.sql:/tmp/dbinit/seed.sql
    - ./dbinit/dbinit.sh:/tmp/dbinit/dbinit.sh
   command: /bin/bash ./tmp/dbinit/dbinit.sh